'use strict';
// Crisis resources shown whenever severity is "critical". VERIFY these numbers before launch and add the
// countries you operate in. They are intentionally kept in code review, not generated by an LLM.
const RESOURCES = {
  FI: {
    country: 'Finland',
    lines: [
      { name: 'Emergency services', phone: '112', note: 'If you or someone else is in immediate danger.' },
      { name: 'MIELI Crisis Helpline (Kriisipuhelin)', phone: '09 2525 0111', note: 'Free crisis support, open 24/7 (Finnish, Swedish, English, Arabic and other languages at set times).', url: 'https://mieli.fi/en/' },
    ],
  },
  DEFAULT: {
    country: 'International',
    lines: [
      { name: 'Local emergency number', phone: '112 / 911 / 999', note: 'If you or someone else is in immediate danger.' },
      { name: 'Find a Helpline', phone: '', note: 'Directory of free, confidential crisis lines by country.', url: 'https://findahelpline.com' },
    ],
  },
};
function getCrisisResources(country) {
  return RESOURCES[country] || RESOURCES.DEFAULT;
}
const CRISIS_MESSAGE =
  "I'm really glad you told me. What you're describing sounds serious, and you deserve support from a real person right now. " +
  'Please contact emergency services or a crisis line (details are shown below). If you can, stay with someone you trust.';
module.exports = { getCrisisResources, CRISIS_MESSAGE };
